spring:
  data:
    mongodb:
      uri: mongodb://root:strongPassword123!@localhost:27017/url_shorter?authSource=admin
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080